In [3]:
import numpy as np
import polars as pl
import torch

df = pl.read_parquet(
    "../data/lichess_puzzles/part_000000000.parquet"
).slice(0, 10)

In [5]:
df.head()

encoded_board,encoded_policy_target,encoded_value_target
binary,binary,binary
"b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…","b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xd2\x10\xd2\x10\xd2\x10\xd2\x10\xd2\x10\xd2\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…",null
"b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…","b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…",null
"b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…","b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00I\x11I\x11I\x11I\x11I\x11I\x11\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…",null
"b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…","b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…",null
"b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…","b""\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00v\x11v\x11v\x11v\x11v\x11v\x11\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00""…",null


In [11]:
decoded_df = df.select(
    pl.col("encoded_board")
    .map_elements(
        lambda x: torch.from_numpy(
            np.frombuffer(x, dtype=np.float16).astype(np.float16)
        )
    )
    .alias("decoded_board"),
    pl.col("encoded_policy_target")
    .map_elements(
        lambda x: torch.from_numpy(
            np.frombuffer(x, dtype=np.float16).astype(np.float16)
        )
    )
    .alias("decoded_policy_target"),
    pl.col("encoded_value_target")
    .map_elements(
        lambda x: torch.from_numpy(
            np.frombuffer(x, dtype=np.float16).astype(np.float16)
        )
    )
    .alias("decoded_value_target"),
)

In [12]:
decoded_df.head()

decoded_board,decoded_policy_target,decoded_value_target
object,object,object
"tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)","tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)",null
"tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)","tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)",null
"tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)","tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)",null
"tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)","tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)",null
"tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)","tensor([0., 0., 0., ..., 0., 0., 0.], dtype=torch.float16)",null
